Repository Evavic44/portfolio-ideas, pull requests merged in 2022-07, with the labels that each got.

#82 Added mshahanwaz.me portfolio
  README.md
Labels: add-portfolio, unordered

#84 🔥 Add Lee's portfolio
  README.md
Labels: add-portfolio

#86 Added parth desai's site
  README.md
Labels: add-portfolio

#88 add bruno_simon's portfolio repositorie
  README.md
Labels: documentation

#89 Add myportfolio to list
  README.md
Labels: add-portfolio

#90 added my portfolio to the list
  README.md
Labels: add-portfolio

#92 Added jacobfv.github.io portfolio
  README.md
Labels: add-portfolio

#93 added my portfolio to the list
  README.md
Labels: add-portfolio
