Repository Evavic44/portfolio-ideas, pull requests merged in 2022-06, with the labels that each got.

#30 :bug: Restore deleted files
  README.md
Labels: bug

#32 :fire: Add Olaolu's portfolio
  README.md
Labels: add-portfolio

#33 add Ahmed Zougari portfolio
  README.md
Labels: add-portfolio

#40 Fix broken lines and indent table
  README.md
Labels: bug

#38 Saikat Roy Portfolio added
  README.md
Labels: add-portfolio

#39 Added my portfolio link
  README.md
Labels: add-portfolio

#42 Added my portfolio details
  README.md
Labels: add-portfolio

#41 Add Sachin Chaurasiya Portfolio
  README.md
Labels: add-portfolio

#36 Added Anish De's portfolio
  README.md
Labels: add-portfolio

#43 Added Md Nayeem's Portfolio
  README.md
Labels: add-portfolio

#44 Update README.md
  README.md
Labels: add-portfolio

#46 Added omar-sherif9992 portfolio sample
  README.md
Labels: add-portfolio

#47 added Robby Leonardi
  README.md
Labels: add-portfolio

#49 Add Jeferson's Portfolio
  README.md
Labels: add-portfolio

#52 Update README.md
  README.md
Labels: add-portfolio

#53 :zap: Indent table lines
  README.md
Labels: documentation

#54 Added ismaellopez.dev portfolio
  README.md
Labels: add-portfolio

#56 Add micahlindely.com
  README.md
Labels: add-portfolio

#61 add dalelarroder.com
  README.md
Labels: add-portfolio

#64 Added two portfolios
  README.md
Labels: add-portfolio

#65 Update my github repo link
  README.md
Labels: enhancement, add-portfolio

#66 update README.md
  README.md
Labels: add-portfolio

#68 Add @AzizStark Portfolio
  README.md
Labels: add-portfolio

#70 Adding Jimmy Soussan / Cozy Codeur Portfolio
  README.md
Labels: add-portfolio

#71 🎯 Add feature template
  .github/ISSUE_TEMPLATE/feature.md
Labels: enhancement

#72 :robot: Add action for stale issues
  .github/stale.yml
Labels: enhancement

#73 Add portfolio
  README.md
Labels: add-portfolio

#74 Update README.md
  README.md
Labels: add-portfolio

#75 🔥 Add Dennis portfolio
  README.md
Labels: add-portfolio

#76 Add Isaac Fayemi's portfolio
  README.md
Labels: add-portfolio

#78 Add protfolio
  README.md
Labels: add-portfolio

#79 Added reubence.com
  README.md
Labels: add-portfolio

#80 Adding nikolovlazar.com
  README.md
Labels: add-portfolio, conflict

#81 Adding pscott.io
  README.md
Labels: add-portfolio, conflict
