Repository Evavic44/portfolio-ideas, pull requests merged in 2022-09, with the labels that each got.

#115 adding eliaz-lr.dev
  README.md
Labels: add-portfolio

#119 feat: :robot: add contributors bot to recognize contributors
  README.md
Labels: documentation, enhancement

#126 feat: add anthony portfolio
  README.md
Labels: add-portfolio

#128 feat: add timlrx's portfolio
  README.md
Labels: add-portfolio

#129 feat: add Thịnh's portfolio
  README.md
Labels: add-portfolio

#130 Add Josiah Etuk's portfolio
  README.md
Labels: add-portfolio

#132 add Mohamud's Protfolio website and it's source code
  README.md
Labels: add-portfolio

#136 Add Maggie Appleton's Porfolio
  README.md
Labels: add-portfolio

#138 feat: setup pre-commit hook for prettier indent
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
Labels: enhancement

#139 Update README.md
  README.md
Labels: add-portfolio
